alias hydra='ssh sofuncheung@hydra.physics.ox.ac.uk'
alias rsync='rsync -vzh'
alias commit='git commit'
alias rsync='rsync -zP'
alias arcus-b='ssh -X lina3603@arcus-b.arc.ox.ac.uk'
alias oscgate='ssh -X lina3603@oscgate.arc.ox.ac.uk'
